- name: conditions
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter your number
    private: false
  tasks:
  - name: please enter the number if it is less than 10
    ansible.builtin.debug:
      msg: "the given number {{my_number}} is less than 10"
    when: my_number | int < 10
  - name: please enter the number if it is greater than or equal to 10
    ansible.builtin.debug:
    when: my_number | int >= 10
