- name: varibales to print
  hosts: web
  vars:
    COURSE: "DevOps"
    DURATION: "140"
    TRAINER: "Siva"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}"


  - name: print the information again and agin
    vars:
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}" 


  - name: print the information agin anf again
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}"       