- name: printing varibales from another file
  hosts: web
  vars_files:
    - vars.yaml
  tasks:
  - name:
    ansible.builtin.debug:
      msg: " Hi I am learning {{COURSE}}, duration is: {{DURATION}}, trainer is:{{TRAINER}}"